## Pytorch Fundamental


In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.6.0+cu124


In [2]:
!nvidia-smi

/bin/bash: line 1: nvidia-smi: command not found


 ## Introduction to Tensors

 ### Creating tensors

In [3]:
#scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [4]:
scalar.ndim

0

In [5]:
# Get tensor back as Python int
scalar.item()

7

In [6]:
# Vector
vector=torch.tensor([7,7])
vector

tensor([7, 7])

In [7]:
# number of dimensions is no of square brackets
vector.ndim

1

In [8]:
vector.shape

torch.Size([2])

In [9]:
# MATRIX
MATRIX = torch.tensor([[7,8],[9,10]])
MATRIX


tensor([[ 7,  8],
        [ 9, 10]])

In [10]:
MATRIX.ndim

2

In [11]:
MATRIX[1]

tensor([ 9, 10])

In [12]:
MATRIX.shape

torch.Size([2, 2])

In [13]:
# TENSOR
TENSOR = torch.tensor([[[1,2,3],[3,6,9],[2,24,5]]])
TENSOR

tensor([[[ 1,  2,  3],
         [ 3,  6,  9],
         [ 2, 24,  5]]])

In [14]:
TENSOR.ndim

3

In [15]:
TENSOR.shape

torch.Size([1, 3, 3])

 ### Random Tensors

In [16]:
 # create random tensor of size (3,4)
 random_tensor = torch.rand(3,4)
 random_tensor

tensor([[0.7756, 0.5167, 0.0866, 0.4000],
        [0.4815, 0.3337, 0.5653, 0.2520],
        [0.7625, 0.1920, 0.4756, 0.9036]])

In [17]:
random_tensor.ndim

2

In [18]:
# Create a random tensor with similar shape to an image tensor.
random_image_size_tensor = torch.rand(size=(3,224,224)) # height, width, color channels (R,G,B)
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([3, 224, 224]), 3)

In [19]:
torch.rand(3,3,4)

tensor([[[0.1076, 0.4282, 0.4083, 0.0563],
         [0.3838, 0.4981, 0.7874, 0.6527],
         [0.4813, 0.1330, 0.8483, 0.5713]],

        [[0.7831, 0.5272, 0.2259, 0.1734],
         [0.8029, 0.5137, 0.0439, 0.0086],
         [0.3768, 0.5406, 0.3835, 0.4331]],

        [[0.4047, 0.8247, 0.9508, 0.7596],
         [0.4947, 0.2623, 0.4544, 0.9585],
         [0.2227, 0.4283, 0.9952, 0.6179]]])

## Zeros and ones

In [20]:
# create a tensor with all zeros
zeros = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [21]:
# Create a tensor of all ones
ones =torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [22]:
ones.dtype

torch.float32

In [23]:
random_tensor.dtype

torch.float32

In [24]:
### Create a range of tensors and tensors-like
torch.arange(0,10)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [25]:
one_to_ten = torch.arange(start=1,end=11)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [26]:
torch.arange(start=0,end=1000,step=77)

tensor([  0,  77, 154, 231, 308, 385, 462, 539, 616, 693, 770, 847, 924])

In [27]:
# Creating tensors like
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor datatypes
**Note:** Tensor datatypes is one of the 3 big errors you'll run into with pytorch & deep learning:
1. Tensors not right datatype
2. Tensors not right shape
3. Tensors not on the right device

In [28]:
# Float32 tensor
float_32_tensor = torch.tensor([3.0,6.0,9.0],
                               dtype=None, # what datatype is the tensor
                               device =None, # What device is your tensor on
                               requires_grad=False) # whether or not to track gradientswith this tensors operations
float_32_tensor.dtype

torch.float32

In [29]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [30]:
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.])

In [31]:
int_32_tensor = torch.tensor([3,6,9], dtype=torch.int32)
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

In [32]:
float_32_tensor * int_32_tensor

tensor([ 9., 36., 81.])

### Getting information from tensors (tensor attributes)

1. Tensors not right datatype - to get datatype from a tensor, can use tensor.dtype
2. Tensors not right shape - to get shape from a tensor, can use tensor.shape
3. Tensors not on the right device - to get device froma tensor, can use tensor.device


In [33]:
# Create a tensor
some_tensor =  torch.rand(3,4)
some_tensor

tensor([[0.7732, 0.5978, 0.9087, 0.3919],
        [0.7532, 0.0197, 0.3962, 0.9788],
        [0.7699, 0.9487, 0.0059, 0.7049]])

In [34]:
# Find out details about some tensor
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of the tensdor: {some_tensor.shape}")
print(f"Device tensor is on: {some_tensor.device}")

tensor([[0.7732, 0.5978, 0.9087, 0.3919],
        [0.7532, 0.0197, 0.3962, 0.9788],
        [0.7699, 0.9487, 0.0059, 0.7049]])
Datatype of tensor: torch.float32
Shape of the tensdor: torch.Size([3, 4])
Device tensor is on: cpu


### Manipulating Tensors (tensor operations)

Tensor operations include :
* Addition
* Subtraction
* Multiplication (element wise)
* Division
* Matrix Multiplication


In [35]:
tensor= torch.tensor([1,2,3])
tensor +100

tensor([101, 102, 103])

In [36]:
# Multiply by ten
tensor*10

tensor([10, 20, 30])

In [37]:
tensor

tensor([1, 2, 3])

In [38]:
tensor=tensor*10

In [39]:
tensor

tensor([10, 20, 30])

In [40]:
# Subtract
tensor-10

tensor([ 0, 10, 20])

In [41]:
# Try out pytorch in built functions
torch.mul(tensor,10)

tensor([100, 200, 300])

In [42]:
torch.add(tensor,10)

tensor([20, 30, 40])

### Matrix Multiplication

Two main ways of performing multiplication in neural networks and deep learning :

1. Element-wise multiplication
2. Matrix Mulriplication (dot product)

There are two main rules that performing matrix multiplication needs to satisfy:
1. The **inner dimensions** must match:
* (3,2) @ (3,2) won't work
* (2,3) @ (3,2) will work
* (3,2) @ (2,3) will work
2. The resulting matrix has the shape of the **outer dimensions**:
* (2,3) @ (3,2) -> (2,2)

In [43]:
torch.matmul(torch.rand(2,3), torch.rand(3,2))

tensor([[1.5051, 1.0003],
        [1.4505, 0.7394]])

In [44]:
#Element wise multiplication
print(tensor,"*",tensor)
print(f"Equals: {tensor*tensor}")

tensor([10, 20, 30]) * tensor([10, 20, 30])
Equals: tensor([100, 400, 900])


In [45]:
# matrix multiplication
torch.matmul(tensor, tensor)

tensor(1400)

In [46]:
%%time
value=0
for i in range(len(tensor)):
  value+=tensor[i]*tensor[i]
print(value)

tensor(1400)
CPU times: user 1.24 ms, sys: 76 µs, total: 1.32 ms
Wall time: 3.98 ms


In [47]:
%%time
torch.matmul(tensor, tensor)

CPU times: user 72 µs, sys: 13 µs, total: 85 µs
Wall time: 90.1 µs


tensor(1400)

### One of the most common errors in deep learning: shape errors

In [48]:
# Shape for matrix multiplication
tensor_A = torch.tensor([[1,2],
                         [3,4],
                         [5,6]])
tensor_B = torch.tensor([[7,10],
                         [8,11],
                         [9,12]])

torch.mm(tensor_A,tensor_B) # torch.matmul

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [49]:
tensor_B.shape, tensor_A.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

To fix our tensor shape issues, we can manipulate the shape of one of our tensors using a **Transpose**

In [50]:
tensor_B.T,tensor_B.T.shape

(tensor([[ 7,  8,  9],
         [10, 11, 12]]),
 torch.Size([2, 3]))

In [51]:
tensor_B, tensor_B.shape

(tensor([[ 7, 10],
         [ 8, 11],
         [ 9, 12]]),
 torch.Size([3, 2]))

In [52]:
# The matrix multiplication operation works when tensor_B is transposed
print(f"Original shapes: tensor_A = {tensor_A.shape}, tensor_B = {tensor_B.shape}")
print(f"New shapes: tensor_A = {tensor_A.shape} (same shape as above), tensor_B.T = {tensor_B.T.shape}")
print(f"Multiplying: {tensor_A.shape} @ {tensor_B.T.shape} <- inner dimensions must match")
print("Output:\n")
torch.mm(tensor_A,tensor_B.T)
print(f"Output shape: {torch.mm(tensor_A,tensor_B.T).shape}")

Original shapes: tensor_A = torch.Size([3, 2]), tensor_B = torch.Size([3, 2])
New shapes: tensor_A = torch.Size([3, 2]) (same shape as above), tensor_B.T = torch.Size([2, 3])
Multiplying: torch.Size([3, 2]) @ torch.Size([2, 3]) <- inner dimensions must match
Output:

Output shape: torch.Size([3, 3])


In [53]:
## Finding the min,max,sum,etc(tensor aggregation)

In [54]:
# create a tensor
x=torch.arange(0,100,10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [55]:
torch.min(x),x.min()

(tensor(0), tensor(0))

In [56]:
torch.max(x),x.max()

(tensor(90), tensor(90))

In [57]:
# Find the mean
torch.mean(x)

RuntimeError: mean(): could not infer output dtype. Input dtype must be either a floating point or complex dtype. Got: Long

In [58]:
x.dtype

torch.int64

In [59]:
# Find the mean - note: the torch.mean() functions requires a tensor of float32 datatypes to work
torch.mean(x.type(torch.float32))

tensor(45.)

In [60]:
x.type(torch.float32).mean()

tensor(45.)

In [61]:
# find the sum
torch.sum(x),x.sum()

(tensor(450), tensor(450))

## Finding the positional min and max

In [62]:
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [63]:
# Find the position in tensor that has the minimum value with argmin()-> returns index
x.argmin()

tensor(0)

In [64]:
x[0]

tensor(0)

In [65]:
# Find the position in tensor that has the maximum value with argmax()
x.argmax()

tensor(9)

In [66]:
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

## Reshaping , stacking , squeezing and unsqueezing tensors

* Reshaping- reshapes an input tensor to a defined shape
* view- Return a view of an input tensor of certain shape but keep the same memory as the orginal
* Stacking - combine multiple tensors on top of each other ore side by side
* Squeeze - removes all 1 dimensions from a tensor
* Unsqueeze - add a 1 dimension to a target tensor
* Permute- return a view of the putput with dimensions permuted(swapped) in a certain way

In [67]:
# Lets create a tensor
x=torch.arange(1.,10.)
x,x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [68]:
# Add an extra dimension
x_reshaped = x.reshape(1,9)
x_reshaped

tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [69]:
#Change the view
z=x.view(1,9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [70]:
# changing z changes x (because a view of a tensor shares the same memory)
z[:,0]=5
z,x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [71]:
# Stack tensors on top of each others
x_stacked = torch.stack([x,x,x,x],dim=1)
x_stacked

tensor([[5., 5., 5., 5.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [4., 4., 4., 4.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.],
        [7., 7., 7., 7.],
        [8., 8., 8., 8.],
        [9., 9., 9., 9.]])

In [72]:
# torch.squeeze() -removes all single dimensions from a target tensor
x_reshaped

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [73]:
x_reshaped.shape

torch.Size([1, 9])

In [74]:
x_reshaped.squeeze()

tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])

In [75]:
x_reshaped.squeeze().shape

torch.Size([9])

In [76]:
print(f"Previous tensor: {x_reshaped}")
print(f"Previous shape : {x_reshaped.shape}")

print(f"New tensor: {x_reshaped.squeeze()}")
print(f"New shape : {x_reshaped.squeeze().shape}")

Previous tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
Previous shape : torch.Size([1, 9])
New tensor: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
New shape : torch.Size([9])


In [77]:
x_squeezed = x_reshaped.squeeze()
x_squeezed.shape

torch.Size([9])

In [78]:
# torch.unsqueeze () - adds a single dimension to a target at a specific dim
print(f"Previous target: {x_squeezed}")
print(f"Previous shape: {x_squeezed.shape}")

# Add an extra dimension with unsqueeze
x_unsqueezed = x_squeezed.unsqueeze(dim=0)
print(f"\nNew tensor: {x_unsqueezed}")
print(f"New shape: {x_unsqueezed.shape}")

Previous target: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
Previous shape: torch.Size([9])

New tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
New shape: torch.Size([1, 9])


In [79]:
# torch.permute - rearranges the dimensiions in a specified order
x_original = torch.rand(size=(224,224,3)) # [height,width,color_channels]

# Permute the original tensor to rearrange the axis (or dim) order
x_permuted = x_original.permute(2,0,1) # shifts axis 0->1, 1->2,2->0

print(f"previous shape: {x_original.shape}")
print(f"New shape: {x_permuted.shape}") # [color_channeled,height width]

previous shape: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])


In [80]:
x_original[0,0,0] = 49

In [81]:
x_permuted[0,0,0],x_original[0,0,0]

(tensor(49.), tensor(49.))

## Indexing (selecting data from tensors)
Indexing with pytorch is similar to indexing with Numpy

In [82]:
#Create a tensor
x=torch.arange(1,10).reshape(1,3,3)

In [83]:
x,x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [84]:
x

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [85]:
# Lets get indexing
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [86]:
x[0][0]

tensor([1, 2, 3])

In [87]:
x[0][1]

tensor([4, 5, 6])

In [88]:
x[0][0][2]

tensor(3)

In [89]:
x[0][2][2]

tensor(9)

In [90]:
# You can also use ":" to select all of target dimension
x[:,0]

tensor([[1, 2, 3]])

In [91]:
# Get all values of 0th and 1st dimensions but only index 1 of 2nd dimension
x[:,:,1]

tensor([[2, 5, 8]])

In [92]:
# Get all values of the 0 dimensions but only the 1 index value of 1st and 2nd dimension
x[:,1,1]

tensor([5])

In [93]:
# get index 0 of 0th and 1st dimension and all values of 2nd dimension
x[0,0,:]

tensor([1, 2, 3])

In [94]:
x[0,:,2]

tensor([3, 6, 9])

## Pytorch tensors and NumPy

Numpy is a popular scientific Python numerical computing library.

And because of this, Pytorch has functionalityto interact with it

* Data in Numpy, want in Pytorch tensor -> 'torch.from_numoy(ndarray)'
* Pytorch tensor -> Numpy -> 'torch.Tensor.numpy()'

In [95]:
import numpy as np

array = np.arange(1.0,8.0)
tensor= torch.from_numpy(array) # warning when converting from numpy -> pytorch,pytorch reflects numpy's default datatype of float64 unless specified otherwise
array,tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [96]:
array.dtype

dtype('float64')

In [97]:
tensor.dtype

torch.float64

In [98]:
torch.arange(1.0,8.0).dtype

torch.float32

In [99]:
# Change the value of array
array= array+1

array,tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [100]:
# Tensor to Numpy array
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [101]:
# Change the tensor what happens to numpy_tensor?
tensor = tensor+1
numpy_tensor,tensor

(array([1., 1., 1., 1., 1., 1., 1.], dtype=float32),
 tensor([2., 2., 2., 2., 2., 2., 2.]))

## Reproducibility (trying to take random out of random )

In short how a neural network learns:

start with random numbers -> tensor operations -> update random numbers to try and make them better representations of data -> again -> again...

To reduce the randomness in neural netwoeks and Pytorch comes the concept of  a **random seed **
Essentially what random seed does is flavour the randomness

In [102]:
random_tensor_A= torch.rand(3,4)
random_tensor_B = torch.rand(3,4)

print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A==random_tensor_B)

tensor([[0.5349, 0.4889, 0.1598, 0.6960],
        [0.7082, 0.9980, 0.1178, 0.2682],
        [0.7177, 0.6950, 0.8731, 0.2443]])
tensor([[0.9676, 0.4020, 0.8512, 0.9681],
        [0.2774, 0.0745, 0.8510, 0.4867],
        [0.3221, 0.0887, 0.4005, 0.0036]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [103]:
# Lets make some random but reproducible tensors
# set the random seed

RANDOM_SEED =42
torch.manual_seed(RANDOM_SEED)

random_tensor_C = torch.rand(3,4)

torch.manual_seed(RANDOM_SEED)
random_tensor_D = torch.rand(3,4)

print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C==random_tensor_D)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


##nRunning tensors and Pytorch objects on the GPUs (and making faster computations)
GPUs = faster computations on numbers thanks to CUDA + NVIDIA hardware + Pytorch working behind the scenes to make everything hunky dory(good)

## 1. Getting a GPU

1. Easiest - Use Google Colab for a free GPU (options to upgrade as well)
2. Use your own GPU - take slittle time to set up and requires the investment of purchasing a GPU. there is lot of options...
3. Use cloud computing - GCP,AWS,AZURE, These services allow you to rent computers in the cloud ans access them


In [104]:
!nvidia-smi

/bin/bash: line 1: nvidia-smi: command not found


In [105]:
### 2. Check for GPu accesss with Pytorch
# Check for GPU access
import torch
torch.cuda.is_available()

False

## For Pytorch since it is capable of running compute on the GPU or CPU, its best practice to setup device agnostic code

In [6]:
# Setup device agnostic code
device = "cuda" if torch.cuda.is_available() else 'cpu'
device

'cpu'

In [107]:
# count number of devices
torch.cuda.device_count()

0

### 3. Putting tensors (and models) pn the GPU
the reason we want our tensors/models on the GPU is because using a GPU results in faster computations

In [108]:
#Create a tensor (default on the CPU)
tensor = torch.tensor([1,2,3])

# Tensor mot on GPU
print(tensor, tensor.device)

tensor([1, 2, 3]) cpu


In [109]:
# Move tensor to GPU (if available)
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3])

### 4.Moving tensors back to CPU

In [110]:
tensor_on_gpu.numpy()

array([1, 2, 3])

In [111]:
# to fix the GPU tensor with Numpy issue, we can first set it to the CPU
tensor_back_on_cpu= tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

array([1, 2, 3])

In [112]:
tensor_on_gpu

tensor([1, 2, 3])

### Exercise

In [113]:
torch.rand(7,7)

tensor([[0.8694, 0.5677, 0.7411, 0.4294, 0.8854, 0.5739, 0.2666],
        [0.6274, 0.2696, 0.4414, 0.2969, 0.8317, 0.1053, 0.2695],
        [0.3588, 0.1994, 0.5472, 0.0062, 0.9516, 0.0753, 0.8860],
        [0.5832, 0.3376, 0.8090, 0.5779, 0.9040, 0.5547, 0.3423],
        [0.6343, 0.3644, 0.7104, 0.9464, 0.7890, 0.2814, 0.7886],
        [0.5895, 0.7539, 0.1952, 0.0050, 0.3068, 0.1165, 0.9103],
        [0.6440, 0.7071, 0.6581, 0.4913, 0.8913, 0.1447, 0.5315]])

In [117]:
a=torch.rand(1,7)
b=torch.rand(1,7)
a,b

(tensor([[0.1088, 0.1637, 0.7025, 0.6790, 0.9155, 0.2418, 0.1591]]),
 tensor([[0.7653, 0.2979, 0.8035, 0.3813, 0.7860, 0.1115, 0.2477]]))

In [118]:
torch.matmul(a,b.T)

tensor([[1.7414]])

In [119]:
torch.manual_seed(0)
torch.rand(7,7)

tensor([[0.4963, 0.7682, 0.0885, 0.1320, 0.3074, 0.6341, 0.4901],
        [0.8964, 0.4556, 0.6323, 0.3489, 0.4017, 0.0223, 0.1689],
        [0.2939, 0.5185, 0.6977, 0.8000, 0.1610, 0.2823, 0.6816],
        [0.9152, 0.3971, 0.8742, 0.4194, 0.5529, 0.9527, 0.0362],
        [0.1852, 0.3734, 0.3051, 0.9320, 0.1759, 0.2698, 0.1507],
        [0.0317, 0.2081, 0.9298, 0.7231, 0.7423, 0.5263, 0.2437],
        [0.5846, 0.0332, 0.1387, 0.2422, 0.8155, 0.7932, 0.2783]])

In [120]:
torch.manual_seed(0)
a=torch.rand(1,7)
torch.manual_seed(0)
b=torch.rand(1,7)
a,b

(tensor([[0.4963, 0.7682, 0.0885, 0.1320, 0.3074, 0.6341, 0.4901]]),
 tensor([[0.4963, 0.7682, 0.0885, 0.1320, 0.3074, 0.6341, 0.4901]]))

In [121]:
torch.matmul(a,b.T)

tensor([[1.5985]])

In [7]:
import torch
torch.cuda.manual_seed(1234)
torch.cuda.get_rng_state()

tensor([210,   4,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0], dtype=torch.uint8)

In [5]:
import torch
torch.manual_seed(7)
a=torch.rand(1,1,1,10)
print(a)
print(a.squeeze())
a.squeeze().shape

tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513])


torch.Size([10])

In [8]:
torch.manual_seed(1234)
a=torch.rand(2,3)
torch.manual_seed(1234)
b= torch.rand(2,3)
a=a.to(device)
b=b.to(device)